### ISSUE TITLE
no csrf found

### ISSUE THREAD

**Issue by senger1985** [soef/ioBroker.alexa#15]
The log-file shows me this note:
no csrf found

alexa.0 | 2018-05-22 12:19:54.336 | error | no csrf found. Check configuration of email/password or cookie
-- | -- | -- | --

host.raspberrypi | 2018-05-22 12:21:52.151 | error | instance system.adapter.alexa.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2018-05-22 12:21:52.151 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:104:9)
host.raspberrypi | 2018-05-22 12:21:52.151 | error | Caught by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:80:11)
host.raspberrypi | 2018-05-22 12:21:52.151 | error | Caught by controller[0]: at emitErrorNT (net.js:1296:8)
host.raspberrypi | 2018-05-22 12:21:52.151 | error | Caught by controller[0]: at TLSSocket.emit (events.js:188:7)
host.raspberrypi | 2018-05-22 12:21:52.151 | error | Caught by controller[0]: at emitOne (events.js:96:13)
host.raspberrypi | 2018-05-22 12:21:52.150 | error | Caught by controller[0]: at TLSSocket.socketErrorListener (_http_client.js:310:9)
host.raspberrypi | 2018-05-22 12:21:52.150 | error | Caught by controller[0]: at ClientRequest.emit (events.js:188:7)
host.raspberrypi | 2018-05-22 12:21:52.150 | error | Caught by controller[0]: at emitOne (events.js:96:13)
host.raspberrypi | 2018-05-22 12:21:52.150 | error | Caught by controller[0]: at ClientRequest. (/opt/iobroker/node_modules/iobroker.alexa/node_modules/alexa-cookie/alexa-cookie.js:54:20)
host.raspberrypi | 2018-05-22 12:21:52.149 | error | Caught by controller[0]: at /opt/iobroker/node_modules/iobroker.alexa/node_modules/alexa-cookie/alexa-cookie.js:127:34
host.raspberrypi | 2018-05-22 12:21:52.146 | error | Caught by controller[0]: TypeError: Cannot read property 'req' of null
alexa.0 | 2018-05-22 12:21:52.096 | error | TypeError: Cannot read property 'req' of null at /opt/iobroker/node_modules/iobroker.alexa/node_modules/alexa-cookie/alexa-cookie.js:127:34 at ClientRequest. (/opt/iobroker/node_mod
alexa.0 | 2018-05-22 12:21:52.094 | error | uncaught exception: Cannot read property 'req' of null
alexa.0 | 2018-05-22 12:19:54.330 | error | no csrf found. Check configuration of email/password or cookie

**Comment by mikiline** [comment]
push, same problem!

**Comment by Apollon77** [comment]
please check https://github.com/Apollon77/ioBroker.alexa and install from there.

Discussion: https://forum.iobroker.net/viewtopic.php?f=37&t=15360
